In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [4]:
data = pd.read_csv('data_clustering1.csv')

In [5]:
x1 = data.x1
x2 = data.x2

In [6]:
C1 = [[1],[1600]]
C2 = [[4],[400]]

In [24]:
def dist_measure(x1,x2,C1,C2):
    dist1 = np.zeros(len(x1))
    dist2 = np.zeros(len(x1))
    for i in range(0,len(x1)):
        dist1[i] = ((x1[i]-C1[0])**2 + (x2[i] - C1[1])**2)**0.5
        dist2[i] = ((x1[i]-C2[0])**2 + (x2[i] - C2[1])**2)**0.5
    return dist1,dist2
def cluster_points(x1,x2,dist1,dist2):
    k = 0
    p = 0
    cluster_1 = np.zeros((len(x1),2))
    cluster_2 = np.zeros((len(x2),2))
    for i in range(0,len(x1)):
        if(dist1[i]<dist2[i]):
            cluster_1[k,0] = x1[i]
            cluster_1[k,1] = x2[i]
            k = k+1
        else:
            cluster_2[p,0] = x1[i]
            cluster_2[p,1] = x2[i]
            p = p+1
    cluster_1 = cluster_1[0:k,:]
    cluster_2 = cluster_2[0:p,:]
    return cluster_1,cluster_2

In [25]:
dist1,dist2 = dist_measure(x1,x2,C1,C2)

In [26]:
cluster_1,cluster_2 = cluster_points(x1,x2,dist1,dist2)

In [27]:
import statistics as st

In [28]:
def calc_mean(cluster_1,cluster_2):
    mean_00 = st.mean(cluster_1[:,0])
    mean_01 = st.mean(cluster_1[:,1])
    mean_10 = st.mean(cluster_2[:,0])
    mean_11 = st.mean(cluster_2[:,1])
    return mean_00,mean_01,mean_10,mean_11

In [29]:
calc_mean(cluster_1,cluster_2)

(2.8582, 1178.88, 2.07515625, 578.1484375)

In [30]:
def k_mean_cluster(x1,x2,C1,C2,iter_max):
    n = 0
    for i in range(0,iter_max):
        dist1,dist2 = dist_measure(x1,x2,C1,C2)
        print(dist_measure(x1,x2,C1,C2))
        cluster_1,cluster_2 = cluster_points(x1,x2,dist1,dist2)
        C1[0],C1[1],C2[0],C2[1] = calc_mean(cluster_1,cluster_2)
        n = n+1;
        print(calc_mean(cluster_1,cluster_2))
    return C1,C2,n
        

In [31]:
dist1,dist2 = dist_measure(x1,x2,C1,C2)

In [32]:
dist1,dist2

(array([149.93024243, 164.93035924,  29.93028203, 265.0716371 ,
        479.93023564, 235.0701348 ,  75.07060408,  80.07017164,
        169.93024127, 169.93027896, 295.06978292,  65.07305816,
        105.07007547,  64.93069698, 332.07006639,  95.06976754,
         65.0697902 ,  84.93028634, 465.0699809 , 369.93026479,
        434.93025692, 444.93045451, 179.93039857, 199.93058315,
        369.93037481, 384.93029798,  19.93023305,  70.07124093,
        299.93024779, 179.93034868,  70.06991868, 300.06976749,
        224.93065206,  20.06999504, 119.93129333, 294.93027298,
        334.93032919, 109.93097646, 194.93076222, 454.93025585,
        419.93033659, 179.93068705, 119.93088496, 534.93027553,
        329.93026468, 134.93023263, 149.93075442, 229.93036371,
        154.93026775,  45.0697747 ,  64.93037169,  50.07140068,
         24.95131885, 160.06983364, 154.93044145,  94.93029127,
        244.93047635,  55.06995987,  70.07189143, 694.93078269,
        534.93083739, 764.93068767, 584.

In [33]:
cluster_1,cluster_2 = cluster_points(x1,x2,dist1,dist2)

In [34]:
cluster_2

array([[  2.8 , 735.  ],
       [  2.7 , 845.  ],
       [  3.  , 780.  ],
       [  2.41, 770.  ],
       [  2.53, 845.  ],
       [  2.63, 830.  ],
       [  2.6 , 880.  ],
       [  3.  , 760.  ],
       [  3.15, 795.  ],
       [  2.64, 680.  ],
       [  3.  , 885.  ],
       [  1.98, 520.  ],
       [  2.05, 680.  ],
       [  2.02, 450.  ],
       [  2.1 , 630.  ],
       [  3.5 , 420.  ],
       [  1.89, 355.  ],
       [  2.42, 678.  ],
       [  2.98, 502.  ],
       [  2.11, 510.  ],
       [  2.53, 750.  ],
       [  1.85, 718.  ],
       [  1.1 , 870.  ],
       [  2.95, 410.  ],
       [  1.88, 472.  ],
       [  3.38, 886.  ],
       [  1.61, 428.  ],
       [  1.95, 392.  ],
       [  1.72, 500.  ],
       [  1.9 , 750.  ],
       [  2.83, 463.  ],
       [  2.42, 278.  ],
       [  2.2 , 714.  ],
       [  2.  , 630.  ],
       [  1.65, 515.  ],
       [  2.2 , 520.  ],
       [  2.2 , 450.  ],
       [  1.78, 495.  ],
       [  1.92, 562.  ],
       [  1.95, 680.  ],


In [35]:
calc_mean(cluster_1,cluster_2)

(2.8582, 1178.88, 2.07515625, 578.1484375)

In [36]:
C1 = [[2.854418604651163],[1214.9302325581396]]
C2 = [[2.116962962962963],[597.8148148148148]]

In [37]:
dist1,dist2 = dist_measure(x1,x2,C1,C2)

In [38]:
dist1,dist2

(array([149.93024243, 164.93035924,  29.93028203, 265.0716371 ,
        479.93023564, 235.0701348 ,  75.07060408,  80.07017164,
        169.93024127, 169.93027896, 295.06978292,  65.07305816,
        105.07007547,  64.93069698, 332.07006639,  95.06976754,
         65.0697902 ,  84.93028634, 465.0699809 , 369.93026479,
        434.93025692, 444.93045451, 179.93039857, 199.93058315,
        369.93037481, 384.93029798,  19.93023305,  70.07124093,
        299.93024779, 179.93034868,  70.06991868, 300.06976749,
        224.93065206,  20.06999504, 119.93129333, 294.93027298,
        334.93032919, 109.93097646, 194.93076222, 454.93025585,
        419.93033659, 179.93068705, 119.93088496, 534.93027553,
        329.93026468, 134.93023263, 149.93075442, 229.93036371,
        154.93026775,  45.0697747 ,  64.93037169,  50.07140068,
         24.95131885, 160.06983364, 154.93044145,  94.93029127,
        244.93047635,  55.06995987,  70.07189143, 694.93078269,
        534.93083739, 764.93068767, 584.

In [39]:
cluster_1,cluster_2 = cluster_points(x1,x2,dist1,dist2)

In [40]:
calc_mean(cluster_1,cluster_2)

(2.8582, 1178.88, 2.07515625, 578.1484375)